import {trivia as starter} from '../data/trivia.js';
import {bankInfo,community} from '../questions.js';
import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {createApp} from '../server.js';
async function fixture(t){let time=10000;const app=createApp({now:()=>time,tickMs:5}),s=app.listen(0,'127.0.0.1');await new Promise(r=>s.once('listening',r));const origin=`http://127.0.0.1:${s.address().port}`;t.after(async()=>{app.locals.dispose();await new Promise(r=>s.close(r));});const a=randomUUID(),b=randomUUID(),c=randomUUID();async function post(token,body){const r=await fetch(origin+'/api/table',{method:'POST',headers:{'Content-Type':'application/json','x-player-token':token},body:JSON.stringify(body)});return {status:r.status,...await r.json()};}async function get(token,code){return fetch(origin+'/api/table?code='+code,{headers:{'x-player-token':token}}).then(r=>r.json());}const made=await post(a,{action:'create',name:'Alice'}),code=made.code;await post(b,{action:'join',code,name:'Bob'});await post(c,{action:'join',code,name:'Cat'});return {a,b,c,post,get,code,origin,advance:n=>time+=n};}
test('multiplayer simultaneous answers and votes; no secret leakage before reveal',async t=>{const f=await fixture(t);let d=await f.post(f.a,{action:'start',code:f.code,round:0});const responses=await Promise.all([[f.a,'One'],[f.b,'Two'],[f.c,'Three']].map(([token,text])=>f.post(token,{action:'answer',code:f.code,round:1,text})));assert.ok(responses.every(r=>r.status===200));d=await f.get(f.a,f.code);assert.equal(d.game.phase,'voting');assert.ok(d.game.options.every(o=>!('truth'in o)&&!('owners'in o)));assert.equal(d.game.question.answer,undefined);const users=[f.a,f.b,f.c];await Promise.all(users.map(async token=>{const x=await f.get(token,f.code);const choice=x.game.options.find(o=>!o.own);const r=await f.post(token,{action:'vote',code:f.code,round:1,option:choice.id});assert.equal(r.status,200);}));assert.equal((await f.get(f.a,f.code)).game.phase,'reveal');});
test('server timers progress without a browser; late submissions fail',async t=>{const f=await fixture(t);await f.post(f.a,{action:'start',code:f.code,round:0});f.advance(60001);await new Promise(r=>setTimeout(r,20));assert.equal((await f.get(f.b,f.code)).game.phase,'voting');const late=await f.post(f.a,{action:'answer',code:f.code,round:1,text:'Late'});assert.equal(late.status,400);f.advance(60001);await new Promise(r=>setTimeout(r,20));assert.equal((await f.get(f.b,f.code)).game.phase,'reveal');});
test('chat is isolated and cannot extend phase deadlines',async t=>{const f=await fixture(t);let d=await f.post(f.a,{action:'start',code:f.code,round:0});const deadline=d.game.deadline;f.advance(10000);d=await f.post(f.a,{action:'chat',code:f.code,text:'Hello <script>not HTML</script>',name:'Spoof'});assert.equal(d.game.deadline,deadline);assert.equal(d.messages[0].name,'Alice');assert.equal((await f.get(f.b,f.code)).messages.length,1);const outsider=randomUUID();assert.equal((await f.get(outsider,f.code)).messages.length,0);assert.equal((await f.post(outsider,{action:'chat',code:f.code,text:'Hi'})).status,400);assert.equal((await f.post(f.a,{action:'chat',code:f.code,text:'x'.repeat(301)})).status,400);});
test('static app and health route work; stale close-phase request cannot end next phase',async t=>{const f=await fixture(t);assert.equal((await fetch(f.origin)).status,200);const info=await fetch(f.origin+'/healthz').then(r=>r.json());assert.equal(info.questions,bankInfo.total);await f.post(f.a,{action:'start',code:f.code,round:0});assert.equal((await f.post(f.a,{action:'closePhase',phase:'writing',round:1,code:f.code})).status,200);assert.equal((await f.post(f.a,{action:'closePhase',phase:'writing',round:1,code:f.code})).status,409);assert.equal((await f.get(f.a,f.code)).game.phase,'voting');});

test('browser history seeds new tables and joining players merge theirs',async t=>{const f=await fixture(t);const facts=starter.filter(q=>q.pack==='facts');const created=await f.post(f.a,{action:'create',name:'Alice',history:[...facts.slice(0,18).map(q=>q.id),'made-up']});assert.equal(created.status,200);const joined=await f.post(f.b,{action:'join',code:created.code,name:'Bob',history:[facts[18].id]});assert.equal(joined.status,200);await f.post(f.a,{action:'settings',code:created.code,round:0,settings:{pack:'facts',mode:'trivia'}});const started=await f.post(f.a,{action:'start',code:created.code,round:0});assert.equal(started.game.question.id,facts[19].id);assert.ok(!('used' in started.game));});
